### ISSUE TITLE
Error in BADC register bits

### ISSUE THREAD

**Issue by hansinator** [adafruit/Adafruit_INA219#14]
I believe you have got an error in the following register bit defines:
    #define INA219_CONFIG_BADCRES_9BIT             (0x0080)  // 9-bit bus res = 0..511
    #define INA219_CONFIG_BADCRES_10BIT            (0x0100)  // 10-bit bus res = 0..1023
    #define INA219_CONFIG_BADCRES_11BIT            (0x0200)  // 11-bit bus res = 0..2047

According to the datasheet, 9 bit resolution needs to be 0x0000. 10 bit should be 0x0080 and 11 bit should be 0x0100. The value you define for 11 bit (0x0200) actually selects 9 bit resolution.

**Comment by deanm1278** [comment]
you're right! fixed!
