### ISSUE TITLE
No "include guards" in Adafruit_INA219.h

### ISSUE THREAD

**Issue by frep** [adafruit/Adafruit_INA219#15]
Using this overall great class gave me the problem of multiple declaration (of this class).

The reason for this is in my opinion the missing include guards in the header file:
using lines like

```
#ifndef ADAFRUIT_INA219_H
#define ADAFRUIT_INA219_H
...
#endif
```

did solve the problem for me. In my opinion should such a include guard be added to the header file.

**Comment by sergio-unparallel** [comment]
I had the same problem and i solved by doing the same. there are another Adafruit libraries that have the same problem.

**Comment by deanm1278** [comment]
done! check latest commit
