### ISSUE TITLE
Bad ina219_powerMultiplier_mW for Calibration_32V_1A

### ISSUE THREAD

**Issue by jakkubu** [adafruit/Adafruit_INA219#24]
`ina219_powerMultiplier_mW` in `.setCalibration_32V_1A()` should be 0.8. Also it needs to be changed from uint32_t to float (or combination of multiplier/divider).

Also in the same line (255) in comments there is a mistake. Now it is `800mW per bit`, it should be `800uW per bit` (`mW` to `uW`).

**Comment by microbuilder** [comment]
Thanks, this should be fixed in https://github.com/adafruit/Adafruit_INA219/commit/f0cfb4976ff6f5cf12b446baf46822503e3822ae
