### ISSUE TITLE
PowerSaving

### ISSUE THREAD

**Issue by Evg33** [adafruit/Adafruit_INA219#27]
Can you add PowerSaving ?
https://forums.adafruit.com/viewtopic.php?f=8&t=104262#p524875
This will save about 0.7mA per INA chip. a serious amount.

**Comment by ladyada** [comment]
please submit a PR - we'd love to check it out :)

**Comment by Evg33** [comment]
@ladyada Hello !
#28

**Comment by hoffmannjan** [comment]
added in #32
