### ISSUE TITLE
Very low shuntvoltage

### ISSUE THREAD

**Issue by Mcpixel53** [adafruit/Adafruit_INA219#29]
Hello,

Any idea what can be causing a very low shunt (and so, load) voltage? just the same as if I didn't connect anything to the shunt resistor.

I'm using this code to get the values:
```

//using setCalibration_32V_1A resolution in setup()

  shuntvoltage = ina219.getShuntVoltage_mV();
  busvoltage = ina219.getBusVoltage_V();
  current_mA = ina219.getCurrent_mA();
  power_mW = ina219.getPower_mW();
  loadvoltage = busvoltage + (shuntvoltage / 1000);
  energy = energy +  loadvoltage * current_mA / 3600; 
```

I have a 4W 3.2Ohm resistance in the negative VIN, the current measurement seems to be correct, around 800mA for Lion battery testing. I am also using an arduino UNO for measurement.

Thanks in advance for any answer!

**Comment by ladyada** [comment]
hiya, this github repo is not for hardware design support - thanks :)

**Comment by Mcpixel53** [comment]
I think you misunderstood me, I'm using this library and didn't touch the module at all. 

It looks pretty straight forward so I thought It could be a firmware issue, I only showed my "hardware" configuration to prove I'm using it right.

Could U tell me if I need to make any special calibration for INA219-GY219 or it is supposed to work with the provided example?

Do U think It may be a hardware issue?   You're welcome =)

**Comment by ladyada** [comment]
hiya if you are using a GY219 module please contact the vendor - they can provide tech support :)

**Comment by Mcpixel53** [comment]
The fix was simply ground the negative with the arduino (\*self-facepalm\*). 
In case it is useful for others wondering the same:
https://cdn-learn.adafruit.com/downloads/pdf/adafruit-ina219-current-sensor-
![image](https://user-images.githubusercontent.com/9295067/55440802-292a9000-55a9-11e9-93c2-82720f252418.png)
