### ISSUE TITLE
busVoltage should be handled as unsigned int

### ISSUE THREAD

**Issue by andreobi** [adafruit/Adafruit_INA219#41]
Error: measured voltages over 16.3V are returned as negative value. 
Problem: the i2c value is treaded as signed INT 
Proposal: change it to unsigned INT as done below and the .h file accordingly.

Andre

uint16_t INA219::busVoltageRaw() {
  _bus_voltage_register = read16(V_BUS_R);
  _overflow = bitRead(_bus_voltage_register, OVF_B);     // overflow bit
  _ready    = bitRead(_bus_voltage_register, CNVR_B);    // ready bit
  return _bus_voltage_register;
}

float INA219::busVoltage() {
  uint16_t temp;
  temp = busVoltageRaw();
  temp >>= 3;
  return (temp * 0.004);
}

**Comment by ladyada** [comment]
thanks, please submit a PR :)

**Comment by andreobi** [comment]
I used an older version. It's already fixed.
