### ISSUE TITLE
Can I use INA219 I2C with UWP

### ISSUE THREAD

**Issue by furkansari96** [adafruit/Adafruit_INA219#46]
Hi,
Can I use this sensor with UWP and Raspberry pi? I saw examples python and arduino but I don't figure out How Can I use with UWP? Do you have any suggestion?
Thank you. Best Regards.

**Comment by ladyada** [comment]
hi we do not have UWP driver. you can use python!

**Comment by furkansari96** [comment]
Hi,
First of all, I really appreciate your answer.  Thank you. So Do you know a
way for UWP? Or I look at different sensor?
Best regard.

1 Şub 2021 Pzt 19:35 tarihinde ladyada <notifications@github.com> şunu
yazdı:
